- name: Add Izzysoft repository GPG key
  ansible.builtin.get_url:
    url: https://apt.izzysoft.de/izzysoft.asc
    dest: "/etc/apt/keyrings/izzysoft.asc"
    mode: '0644'
  when: monitorix_izzysoft_repo_state == 'present'

- name: Remove Izzysoft repository GPG key
  ansible.builtin.file:
    path: "/etc/apt/keyrings/izzysoft.asc"
    state: absent
  when: monitorix_izzysoft_repo_state == 'absent'

- name: Manage Izzysoft apt repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/izzysoft.asc] https://apt.izzysoft.de/ubuntu generic universe"
    state: "{{ monitorix_izzysoft_repo_state }}"

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
  changed_when: false
