- name: install apt-transport-https
  package:
    name: apt-transport-https

- name: add apt signing keys
  apt_key:
    url: https://apt.izzysoft.de/izzysoft.asc

- name: add apt repositories
  apt_repository:
    repo: deb https://apt.izzysoft.de/ubuntu generic universe

- name: apt-get update
  apt:
    update_cache: yes
  when: "ansible_os_family == 'Debian'"
  changed_when: false

