---
- include_vars: "{{ ansible_distribution }}/{{ ansible_distribution_version }}.yml"

- include_tasks: "{{ ansible_os_family }}.yml"

- name: install packages
  package:
    name: monitorix

- name: configure monitorix
  template:
    src: 01-custom.conf.j2
    dest: /etc/monitorix/conf.d/01-custom.conf
  notify: restart monitorix

- name: creating directory for alerting scripts
  file:
    path: "{{ monitorix_alerting_scripts_base_path }}"
    state: directory

- name: deploy alerting scipts
  template:
    src: "{{ item.script }}.j2"
    dest: "{{ monitorix_alerting_scripts_base_path }}{{ item.script }}_{{ item.list_item_alt_name }}"
    mode: '0744'
  with_items:
  - "{{ monitorix_alerting_fs_final }}"
  when: item.alert
