---

- include_tasks: "{{ ansible_os_family }}.yml"

- name: install packages
  package:
    name: monitorix

- name: configure monitorix
  template:
    src: monitorix.conf.j2
    dest: /etc/monitorix/monitorix.conf
  notify: restart monitorix

- name: configure monitorix
  template:
    src: 00-debian.conf.j2
    dest: /etc/monitorix/conf.d/00-debian.conf
  notify: restart monitorix
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: creating directory for alerting scripts
  file:
    path: "{{ monitorix_alerting_scripts_base_path }}"
    state: directory

- name: deploy alerting scipts
  template:
    src: "{{ item.script }}.j2"
    dest: "{{ monitorix_alerting_scripts_base_path }}{{ item.script }}_{{ item.list_item_alt_name }}"
    mode: 0744
  with_items:
    - "{{ monitorix_alerting_fs_final }}"
  when: item.alert